name: "Composer TF Apply"

on:
  push:
    branches: ["*"]

jobs:
  composer-apply:
    name: "Bucket Apply"
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.CREDENTIALS_INFRA }}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform -chdir=./envs/dev/bucket init
        env:
          GCP_SA_KEY: ${{ secrets.CREDENTIALS_INFRA }}

      - name: Terraform Plan
        run: terraform -chdir=envs/dev/bucket plan -lock=false -out=tfplan
        env:
          GCP_SA_KEY: ${{ secrets.CREDENTIALS_INFRA }}

      - name: Terraform Apply
        run: terraform -chdir=envs/dev/bucket apply -auto-approve -lock=false
        env:
          GCP_SA_KEY: ${{ secrets.CREDENTIALS_INFRA }}